spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/exam
    username: kekee
    password: Kek@0724
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  mapper-locations: com.example.meituan.mapper/*.xml
  type-aliases-package: com.example.meituan.mapper